WIP - Initial support for OpenACC syntax
krvajal/vscode-fortran-support pull request #224
Opened 2021-04-14 17:02 UTC by jefflarkin

This PR creates initial support for OpenACC directives, based on the existing OpenMP syntax. 

Changes:
Made OpenMP sentinel less greedy
Added initial support for OpenACC directives

WIP:
Some clauses not matching properly. 
* private/firstprivate
* data clauses (copyin and the rest)
* perhaps others
Directives with optional arguments may not match properly, still testing.

Future work:
I would love to implement the actual grammar so that clauses that are invalid on particular directives do not match. Currently this does the same simple matching as the OpenMP syntax on which I based this change.

2021-04-17 08:06 UTC, gnikit commented
The one thing that would be useful would be to add a Fortran file where you test these directives. I added some myself under `test/resources` I found it extremely helpful while making changes to visually inspect that I have not broken anything and it will be useful in the future when we figure out how we can unittest the syntax highlighting.

Also, as I said in my tracking issue, could you think of any cases where the OpenMP functionality would fail with the change that you made?

2021-04-17 12:18 UTC, jefflarkin commented
Sure. I will add the test cases I was using when I'm back at that computer on Monday.

Regarding the OpenMP matching, what I found was that with the existing matching it would sometimes erroneously match an OpenACC directive with the OpenMP syntax. For instance 'acc parallel do' is not valid, but it would get matched from the OpenMP. I made the matching less greedy and as best as I could tell still match correctly.

2021-04-19 20:15 UTC, jefflarkin commented
I submitted #225 related to line continuations, but since this is true for the existing OpenMP and OpenACC, I don't think it should block the merging of this issue. The fix should be the same for each.

2021-06-29 13:59 UTC, jefflarkin commented
Fixes #225

2021-06-29 14:00 UTC, jefflarkin commented
@gnikit I believe this is ready to merge and put out in the market. Do you agree?

2021-06-30 12:01 UTC, gnikit requested changes
Awesome job @jefflarkin. Thanks for taking the time to do this.
I had a quick play around with my OpenMP and the added OpenACC test that was added and all looks good.

It truly is a shame that we cannot unify the openmp.json and openacc.json into one file since they have a lot of duplicate code, but I think it is better to add support now for the openacc and improve on it in the future, if need be.

I left some minor comments, but no major changes. 

I look forward to seeing this in master.

2021-06-30 13:39 UTC, jefflarkin commented on syntaxes/openacc_lang.json
> +	},
Fixing in next push.

2021-06-30 13:39 UTC, jefflarkin commented on syntaxes/openmp_lang.json
> +	},
Fixing in next push.

2021-06-30 13:41 UTC, jefflarkin commented on syntaxes/openmp_lang.json
> +      "begin": "(?i)\\G(\\$(omp\\b)&?)",
This is what I discussed previously about the OpenMP matcher being too greedy. With that extra `?` it will incorrectly match `acc parallel do` using the OpenMP matcher (it's not valid OpenACC). Removing that `?` fixed the issues in all test codes I tried and I found no cases where it caused correct matching to fail.

2021-06-30 14:08 UTC, gnikit commented on syntaxes/openmp_lang.json
> +      "begin": "(?i)\\G(\\$(omp\\b)&?)",
Ok I understand, that is fine by me (I had forgotten about our previous chat)

2021-06-30 14:12 UTC, gnikit approved these changes

2021-06-30 15:36 UTC, gnikit commented
I don't know if @krvajal you want to have a look. All is good. I will add the updated CHANGELOG in a bit.

2021-06-30 16:43 UTC, jefflarkin commented
Fixes #184

2021-06-30 19:01 UTC, merged